import asyncio
from itertools import count
class Request:
    prompt: str    # Prompt token ids, generated by the tokenizer upon request arrival
    prompt_len: int     # len(prompt_token_ids)
    temperature: float
    max_token:int
    ingore_eos: bool
    finished_event: asyncio.Event       
                                        

    request_id: int     # Request ID, within range [0, max_seqs_in_block_table).
                        # Generated before being prefilled, and used as the index
                        # into the block table
    output_token_ids: list[int]     # Output token ids
    output:str
    counter = count()
    def __init__(self, prompt:str, temperature: float=0, max_tokens:int = 10,ignore_eos:bool = False):
        self.prompt = prompt
        self.token_ids = None
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.ignore_eos = ignore_eos
        self.finished_event = asyncio.Event()
        self.request_id = next(Request.counter)
        self.output_token_ids = []
        self.output = ""
        self.time_usage = None
        self.prefix_cached = 0
    
    def output_dict(self):
        return {'prompt':prompt}
    
